2024-09-08 12:46:08,495 arches.app.utils.data_management.resource_graphs.importer ERROR    "'https://takin.solutions/ontologies/rdm/R1_Linguistic_Authority_Document' is not a valid Delving CRM v7.1.2 ontology class"
Traceback (most recent call last):
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/utils/data_management/resource_graphs/importer.py", line 128, in import_graph
    graph.save()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 478, in save
    self.validate()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 1696, in validate
    raise GraphValidationError(
arches.app.models.graph.GraphValidationError: "'https://takin.solutions/ontologies/rdm/R1_Linguistic_Authority_Document' is not a valid Delving CRM v7.1.2 ontology class"
2024-09-08 13:01:23,326 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-08 13:01:35,600 arches.app.utils.data_management.resource_graphs.importer ERROR    "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E33_E41_Linguistic_Appellation' and                                 Entity range 'http://www.w3.org/2001/XMLSchema#string' cannot                                 be related via Property 'http://www.cidoc-crm.org/cidoc-crm/P190_has_symbolic_content'."
Traceback (most recent call last):
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/utils/data_management/resource_graphs/importer.py", line 128, in import_graph
    graph.save()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 478, in save
    self.validate()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 1722, in validate
    raise GraphValidationError(
arches.app.models.graph.GraphValidationError: "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E33_E41_Linguistic_Appellation' and                                 Entity range 'http://www.w3.org/2001/XMLSchema#string' cannot                                 be related via Property 'http://www.cidoc-crm.org/cidoc-crm/P190_has_symbolic_content'."
2024-09-08 13:01:36,027 arches.app.utils.data_management.resource_graphs.importer ERROR    "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E33_E41_Linguistic_Appellation' and                                 Entity range 'http://www.w3.org/2001/XMLSchema#string' cannot                                 be related via Property 'http://www.cidoc-crm.org/cidoc-crm/P190_has_symbolic_content'."
Traceback (most recent call last):
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/utils/data_management/resource_graphs/importer.py", line 128, in import_graph
    graph.save()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 478, in save
    self.validate()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 1722, in validate
    raise GraphValidationError(
arches.app.models.graph.GraphValidationError: "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E33_E41_Linguistic_Appellation' and                                 Entity range 'http://www.w3.org/2001/XMLSchema#string' cannot                                 be related via Property 'http://www.cidoc-crm.org/cidoc-crm/P190_has_symbolic_content'."
2024-09-08 13:06:47,532 arches.app.utils.data_management.resource_graphs.importer ERROR    "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E33_Linguistic_Object' and                                 Entity range 'http://www.w3.org/2000/01/rdf-schema#Literal' cannot                                 be related via Property 'http://www.w3.org/2000/01/rdf-schema#label'."
Traceback (most recent call last):
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/utils/data_management/resource_graphs/importer.py", line 128, in import_graph
    graph.save()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 478, in save
    self.validate()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 1722, in validate
    raise GraphValidationError(
arches.app.models.graph.GraphValidationError: "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E33_Linguistic_Object' and                                 Entity range 'http://www.w3.org/2000/01/rdf-schema#Literal' cannot                                 be related via Property 'http://www.w3.org/2000/01/rdf-schema#label'."
2024-09-08 13:16:55,009 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-08 14:24:21,631 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-08 14:24:32,794 arches.app.utils.data_management.resource_graphs.importer ERROR    "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E52_Time-Span' and                                 Entity range 'http://www.w3.org/2001/XMLSchema#dateTime' cannot                                 be related via Property 'http://www.cidoc-crm.org/cidoc-crm/P82a_begin_of_the_begin'."
Traceback (most recent call last):
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/utils/data_management/resource_graphs/importer.py", line 128, in import_graph
    graph.save()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 478, in save
    self.validate()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 1722, in validate
    raise GraphValidationError(
arches.app.models.graph.GraphValidationError: "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E52_Time-Span' and                                 Entity range 'http://www.w3.org/2001/XMLSchema#dateTime' cannot                                 be related via Property 'http://www.cidoc-crm.org/cidoc-crm/P82a_begin_of_the_begin'."
2024-09-08 15:13:38,741 arches.app.views.search ERROR    Node matching query does not exist.
Traceback (most recent call last):
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/views/search.py", line 326, in search_results
    search_filter.append_dsl(search_results_object, permitted_nodegroups, include_provisional)
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/search/components/advanced_search.py", line 36, in append_dsl
    node = models.Node.objects.get(pk=key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
arches.app.models.models.Node.DoesNotExist: Node matching query does not exist.
2024-09-08 15:21:31,033 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-08 15:31:51,984 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-08 15:33:29,116 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-08 15:35:13,167 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-08 16:17:35,824 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-09 14:44:53,997 arches.app.utils.data_management.resource_graphs.importer ERROR    "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E33_E41_Linguistic_Appellation' and                                 Entity range 'http://www.w3.org/2001/XMLSchema#string' cannot                                 be related via Property 'http://www.cidoc-crm.org/cidoc-crm/P190_has_symbolic_content'."
Traceback (most recent call last):
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/utils/data_management/resource_graphs/importer.py", line 128, in import_graph
    graph.save()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 478, in save
    self.validate()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 1722, in validate
    raise GraphValidationError(
arches.app.models.graph.GraphValidationError: "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E33_E41_Linguistic_Appellation' and                                 Entity range 'http://www.w3.org/2001/XMLSchema#string' cannot                                 be related via Property 'http://www.cidoc-crm.org/cidoc-crm/P190_has_symbolic_content'."
2024-09-14 02:36:23,332 arches.app.utils.data_management.resource_graphs.importer ERROR    "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E61_Time_Primitive' and                                 Entity range 'http://www.cidoc-crm.org/cidoc-crm/E55_Type' cannot                                 be related via Property 'http://www.cidoc-crm.org/cidoc-crm/P2_has_type'."
Traceback (most recent call last):
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/utils/data_management/resource_graphs/importer.py", line 128, in import_graph
    graph.save()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 478, in save
    self.validate()
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/graph.py", line 1722, in validate
    raise GraphValidationError(
arches.app.models.graph.GraphValidationError: "Your graph isn't semantically valid. Entity domain 'http://www.cidoc-crm.org/cidoc-crm/E61_Time_Primitive' and                                 Entity range 'http://www.cidoc-crm.org/cidoc-crm/E55_Type' cannot                                 be related via Property 'http://www.cidoc-crm.org/cidoc-crm/P2_has_type'."
2024-09-14 03:32:12,181 arches.app.views.tile ERROR    Unable to save. Please verify your input is valid [Tile id: ]                      [Exception message: TileValidationError: edtf error, 1900-0-01  - Incorrect Extended Date Time Format. See http://www.loc.gov/standards/datetime/ for supported formats. Unable to save.]                      [Exception trace: Traceback (most recent call last):
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/views/tile.py", line 144, in post
    tile.save(request=request, transaction_id=transaction_id)
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/tile.py", line 456, in save
    self.validate([], request=request)
  File "/Users/tw/Projects/ArchesProjects/NoordBrabant/brabantse_gebouwen/.venv/lib/python3.11/site-packages/arches/app/models/tile.py", line 350, in validate
    raise TileValidationError(_("{0}".format(error_instance["message"])))
arches.app.models.tile.TileValidationError: 'edtf error, 1900-0-01  - Incorrect Extended Date Time Format. See http://www.loc.gov/standards/datetime/ for supported formats. Unable to save.'
]
2024-09-15 09:13:29,315 arches.app.search.search WARNING  2024-09-15 09:13:29.315334: WARNING: failed to index document: {'id': '85394923-1c84-4114-9fdf-bf3033597519', 'conceptid': 'd2adbeb1-7093-451e-85b4-aa257f01a15e', 'type': 'prefLabel', 'category': 'label', 'value': 'Event Role Type', 'language': 'en', 'top_concept': 'd2adbeb1-7093-451e-85b4-aa257f01a15e'} 
Exception detail: ApiError(429, 'cluster_block_exception', 'index [brabantse_gebouwen_concepts] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];')

2024-09-15 09:15:11,848 arches.app.search.search WARNING  2024-09-15 09:15:11.848342: WARNING: failed to index document: {'id': 'bddcbc77-2d1e-46d7-8e08-bbebb1e25a2f', 'conceptid': 'e2b0bd0f-d445-41b1-8f7f-0d983e7da94f', 'type': 'prefLabel', 'category': 'label', 'value': 'Event Role Type', 'language': 'en', 'top_concept': 'e2b0bd0f-d445-41b1-8f7f-0d983e7da94f'} 
Exception detail: ApiError(429, 'cluster_block_exception', 'index [brabantse_gebouwen_concepts] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];')

2024-09-15 14:26:31,115 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-15 14:26:48,862 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(2afd9541-65c9-4620-ae30-821258d37f2a) is not present in table "concepts".

2024-09-15 14:26:48,932 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(23bdf593-4c71-43f7-99d7-ce9eb0c6cdeb) is not present in table "concepts".

2024-09-15 14:28:22,428 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-15 14:28:29,718 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(23bdf593-4c71-43f7-99d7-ce9eb0c6cdeb) is not present in table "concepts".

2024-09-15 14:28:29,753 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(2afd9541-65c9-4620-ae30-821258d37f2a) is not present in table "concepts".

2024-09-15 14:33:44,113 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-15 14:33:52,864 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(23bdf593-4c71-43f7-99d7-ce9eb0c6cdeb) is not present in table "concepts".

2024-09-15 14:33:52,900 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(2afd9541-65c9-4620-ae30-821258d37f2a) is not present in table "concepts".

2024-09-15 14:36:29,379 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-15 14:36:37,141 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(2afd9541-65c9-4620-ae30-821258d37f2a) is not present in table "concepts".

2024-09-15 14:36:37,320 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(23bdf593-4c71-43f7-99d7-ce9eb0c6cdeb) is not present in table "concepts".

2024-09-15 14:42:36,386 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-15 14:42:43,489 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(2afd9541-65c9-4620-ae30-821258d37f2a) is not present in table "concepts".

2024-09-15 14:42:43,515 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(23bdf593-4c71-43f7-99d7-ce9eb0c6cdeb) is not present in table "concepts".

2024-09-15 14:47:59,343 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-15 14:48:07,133 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(2afd9541-65c9-4620-ae30-821258d37f2a) is not present in table "concepts".

2024-09-15 14:48:07,166 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(23bdf593-4c71-43f7-99d7-ce9eb0c6cdeb) is not present in table "concepts".

2024-09-15 14:50:23,172 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-15 14:50:30,732 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(23bdf593-4c71-43f7-99d7-ce9eb0c6cdeb) is not present in table "concepts".

2024-09-15 14:50:30,764 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(2afd9541-65c9-4620-ae30-821258d37f2a) is not present in table "concepts".

2024-09-15 15:26:28,259 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-16 05:34:39,865 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 09:12:05,115 arches.app.utils.skos WARNING  
The SKOS file "Dedication Subject Type.xml" appears to have orphaned concepts.
2024-09-26 15:17:26,806 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 15:17:36,024 arches.app.utils.skos WARNING  
The SKOS file "Brabantse Gebouwen.xml" appears to have orphaned concepts.
2024-09-26 15:17:36,213 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(7da08de2-8f46-46be-a67f-4235b246010a) is not present in table "concepts".

2024-09-26 15:17:36,227 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(dd722800-d57d-4085-8a0f-004c03ca1b40) is not present in table "concepts".

2024-09-26 15:17:36,229 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(9a7d9fe5-a982-47c4-8f6a-f8f5cbb65578) is not present in table "concepts".

2024-09-26 15:17:36,241 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(d790adfa-6332-47c1-91e0-493c4accefe1) is not present in table "concepts".

2024-09-26 15:17:36,246 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(9f567b55-ceec-4461-b7d2-c73d6b06a6d2) is not present in table "concepts".

2024-09-26 15:17:36,253 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(13ffbad5-492d-41f7-8db2-a8f0ff31d820) is not present in table "concepts".

2024-09-26 15:17:36,270 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(b4beedc2-7adf-408e-8812-935e63898f5e) is not present in table "concepts".

2024-09-26 15:17:36,286 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(44d943b6-c77f-4ec6-b372-693962ae7406) is not present in table "concepts".

2024-09-26 15:17:36,291 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(c172f5f6-d770-4ded-9a84-250922abf516) is not present in table "concepts".

2024-09-26 15:17:36,324 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(a8192e9b-c51b-42c2-9bb1-d88da37c32d3) is not present in table "concepts".

2024-09-26 15:17:36,342 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(477b5e08-cfde-495b-beeb-82560b805dee) is not present in table "concepts".

2024-09-26 15:17:36,365 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(9067b30b-b76d-4149-975b-ceccb3d040a0) is not present in table "concepts".

2024-09-26 15:17:36,373 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(8a5351c4-0d51-4670-8046-2e6aafabbfe9) is not present in table "concepts".

2024-09-26 15:17:36,394 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(c44e4cca-d283-44aa-89b9-2ac26f32f892) is not present in table "concepts".

2024-09-26 15:17:36,396 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(36da50a6-44f1-46db-9602-cd777267b1d1) is not present in table "concepts".

2024-09-26 15:17:36,408 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(f2d26877-f91d-4633-ad6c-b50e45931d63) is not present in table "concepts".

2024-09-26 15:17:36,415 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(cc8631de-63a0-4197-9f53-00c19efbd34f) is not present in table "concepts".

2024-09-26 15:17:36,419 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(739af934-af35-482c-a4df-4496a3658520) is not present in table "concepts".

2024-09-26 15:17:36,435 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(c422d4a9-6526-42ae-b8db-b6614b270c87) is not present in table "concepts".

2024-09-26 15:17:36,462 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(04241297-6478-454f-929d-d80558ab0b55) is not present in table "concepts".

2024-09-26 15:17:36,482 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(40b37ac2-251a-44d1-8894-8e5425874f43) is not present in table "concepts".

2024-09-26 15:17:36,486 arches.app.utils.skos WARNING  insert or update on table "relations" violates foreign key constraint "relations_conceptidto_6fb05b5e_fk_concepts_conceptid"
DETAIL:  Key (conceptidto)=(34a6124f-756f-4633-b54b-853f7d2f2f43) is not present in table "concepts".

2024-09-26 15:18:45,904 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 15:18:54,442 arches.app.utils.skos WARNING  
The SKOS file "Brabantse Gebouwen.xml" appears to have orphaned concepts.
2024-09-26 15:39:03,780 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 15:39:12,014 arches.app.utils.skos WARNING  
The SKOS file "Brabantse Gebouwen.xml" appears to have orphaned concepts.
2024-09-26 15:42:45,806 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 15:48:52,947 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 15:52:04,887 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 15:52:17,595 arches.app.utils.skos WARNING  
The SKOS file "Brabantse Gebouwen.xml" appears to have orphaned concepts.
2024-09-26 16:03:24,746 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 16:03:38,466 arches.app.utils.skos WARNING  
The SKOS file "Brabantse Gebouwen.xml" appears to have orphaned concepts.
2024-09-26 16:06:15,803 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 16:09:53,113 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 16:11:03,014 arches.app.utils.skos WARNING  
The SKOS file "Brabantse Gebouwen.xml" appears to have orphaned concepts.
2024-09-26 16:15:38,325 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 16:18:50,113 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
2024-09-26 16:24:00,331 arches.app.utils.data_management.resource_graphs.importer WARNING  No ontologies have been loaded. Any GraphModel that depends on an ontology cannot be loaded.
